on: '3'

services:
  ots-pg:
    build: 
      context: /opt/OpenTileServer/ots-pg/
      dockerfile: /opt/OpenTileServer/ots-pg/Dockerfile
    image: gps4pets/ots-pg
    env_file:
      - stack.env
    volumes:
      - /opt/OpenTileServer/pg-data:/var/lib/postgresql/data
    restart: always
    container_name: ots-pg
    hostname: ots-pg
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -h ots-pg -U ${POSTGRES_USER}
      interval: 60s
      retries: 2
      timeout: 10s
    networks:
      - n7m_osm_bridge

  ots-tile:
    build: 
      context: /opt/OpenTileServer/ots-tile/
      dockerfile: /opt/OpenTileServer/ots-tile/Dockerfile
    image: gps4pets/ots-tile
    env_file:
      - stack.env
    volumes:
      - /opt/OpenTileServer/tiles-data:/var/cache/renderd/tiles
    ports:
      - 8181:80
    healthcheck:
      test: "curl -f http://localhost"
    restart: always
    container_name: ots-tile
    hostname: ots-tile
    depends_on:
      - "ots-pg"
    networks:
      - n7m_osm_bridge

networks:
  n7m_osm_bridge:
    external: true

