version: '3'

services:
  osm-pg:
    build: 
      context: /opt/OpenTileServer/pg/
      dockerfile: /opt/OpenTileServer/pg/Dockerfile
    image: acugis/pg:latest
    volumes:
      - /opt/OpenTileServer/pg-data:/var/lib/postgresql/data
    restart: always
    container_name: osm-pg
    hostname: pg
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -h pg -U ${POSTGRES_USER}
      interval: 60s
      retries: 2
      timeout: 10s
    networks:
      - n7m_osm_bridge

  osm-tile:
    build: 
      context: /opt/OpenTileServer/tile/
      dockerfile: /opt/OpenTileServer/tile/Dockerfile
    image: acugis/opentileserver:latest
    volumes:
      - /opt/OpenTileServer/tiles-data:/var/cache/renderd/tiles
    ports:
      - 8181:80
    restart: always
    container_name: osm-tile
    depends_on:
      - "osm-pg"
    networks:
      - n7m_osm_bridge

networks:
  n7m_osm_bridge:
    external: true

